name: prayer_vs
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  adhan: ^2.0.0+1
  intl: ^0.19.0
  sqflite: ^2.2.0
  path: ^1.8.0
  path_provider_android: ^2.2.12
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.9
  android_alarm_manager_plus: ^4.0.4
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  permission_handler: ^10.2.0
  flutter_timezone: ^2.0.0
  fl_chart: ^0.69.0
  google_mobile_ads: ^5.2.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  hive_generator: ^2.0.0


  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/sounds/notification_sound.mp3


  uses-material-design: true

  